### ISSUE TITLE
about the number of parameter adjustment.

### ISSUE THREAD

**Issue by jdily** [CyberAgentAILab/layout-dm#11]
Hi, thx for sharing the nice work.
Recently, I want to reproduce the LayoutGAN++ experiment in Table 1 (using the source code provided by LayoutGAN++).
However, I think because the number of parameters are not the same (I think the original LayoutGAN++ parameters are way more than the simplified model used in this paper).
I am wondering if you can share the simplified version of LayoutGAN++ as well? 
Or you can share the simplified architecture so that I can perform experiment on it?

thank you!!

**Comment by naoto0804** [comment]
Hi, I'll get you back when I'm back from CVPR

**Comment by naoto0804** [comment]
As you guessed, we did experiments for LayoutGAN++ with its codebase. This is because of practical implementation reasons; GANs are complex compared to [simple forward-backward workflow](https://github.com/CyberAgentAILab/layout-dm/blob/main/src/trainer/trainer/main.py#L225-L229) and I found it too hard to integrate GANs with this framework.

Below are the instructions, sorry for the inconvenience.
(i) We use `num_layers=4`, `d_model=512`, `nhead=8` for the [generator](https://github.com/ktrk115/const_layout/blob/master/model/layoutganpp.py#L9)
(ii) copy this repo's code for data preprocessing and loading pipeline.
(iii) add some codes to dump predictions (if you want to evaluate the result with [eval.py](https://github.com/CyberAgentAILab/layout-dm/blob/main/eval.py))

**Comment by jdily** [comment]
Hi, thank your for your quick reply.
I will try it follow your instructions, and I will ask questions if I still have some problems reproducing that results. :)
