### ISSUE TITLE
Fine tuning or Transfer learning

### ISSUE THREAD

**Issue by kietbg0079** [CyberAgentAILab/layout-dm#16]
I want to use layoutDM to generate layouts based on my poster dataset. But the problem here my dataset is very small (contains only 1000 layouts). Is it possible to fine-tune or transfer learning the Rico and Publaynet pre-trained model to adapt to my task?

**Comment by Lanjiong-Li** [comment]
Can you sucessfully run 'bash bin/train.sh <yourowndataset> layoutdm' ?

**Comment by kietbg0079** [comment]
> Can you sucessfully run 'bash bin/train.sh layoutdm' ?

yes, I can

**Comment by Lanjiong-Li** [comment]
> > Can you sucessfully run 'bash bin/train.sh layoutdm' ?
> 
> yes, I can

Could I ask how long does it take for u to train FID model?

**Comment by naoto0804** [comment]
Hi @kietbg0079, thank you for visiting our repo!

> Is it possible to fine-tune or transfer learning the Rico and Publaynet pre-trained model to adapt to my task?

Although I haven't tried, I think it is possible. Please adjust the feature dimension in the category embedding/prediction part if your dataset's categories do not match the pre-training dataset.
Since transfer learning/fine-tuning is less explored in layout generation, I'd love to hear the result if possible!
