### ISSUE TITLE
why beta parameter in transition matrix is so small

### ISSUE THREAD

**Issue by jiangzhengguo** [CyberAgentAILab/layout-dm#4]
I notice that in your code, att is from 0.99999 to 0.000009, ctt is from 0.000009 to 0.99999, so the btt=(1-att-ctt)/N is less then 1e-6! It is almost impossible to jump to another token except <mask>?

**Comment by naoto0804** [comment]
Good question. Indeed, our codebase is based on VQDiffusion. I guess the actual probability to switch is bigger than stated because of unexpressed stochasticity in implementation of VQDiffusion. I found that [log_sample_categorical](https://github.com/microsoft/VQ-Diffusion/blob/e227b2643f2842d562706534cb1c46301e116b1f/image_synthesis/modeling/transformers/diffusion_transformer.py#L331-L336) function involves Gumbel-max trick to sample a one-hot vector in a stochastic manner.
